### ISSUE TITLE
Same block edges

### ISSUE THREAD

**Issue by giorgioangel** [schillij95/ThaumatoAnakalyptor#24]
https://github.com/schillij95/ThaumatoAnakalyptor/blob/85e7c54ae7192e08cee0d438e6824f81e6d042cb/ThaumatoAnakalyptor/instances_to_graph.py#L943

Why?

**Comment by giorgioangel** [comment]
Loading the graph problem without same_block_edges gives the same results. Those edges are the ones deleted after the first pruning step.

**Comment by schillij95** [comment]
There are two types of edges in the graph:
1. Connecting adjacent + overlapping subvolume patches of the same sheet (other_block_edges)
2. Connecting patches in the same subvolume that are on adjacent sheets. ie have a winding angle of around +- 360 degree (same_block_edges)

The 2. type of edges should in theory add more information to the graph problem.

**Comment by schillij95** [comment]
Issue #23 might be related to this. It might be that the 2.5D surface is used to generate the same block edges.

**Comment by schillij95** [comment]
https://github.com/schillij95/ThaumatoAnakalyptor/blob/2f15964e1faa535ac948d1f64568aeb793f26ed0/ThaumatoAnakalyptor/instances_to_graph.py#L723

No wonder the same block edges werent working. they were saved as other block edges.
