### ISSUE TITLE
Converting between graph .npz and .bin?

### ISSUE THREAD

**Issue by terramars** [schillij95/ThaumatoAnakalyptor#36]
The new sheet stitching solution uses .npz for its output, but all other code assumes either binary or pickle graph format.  How do we convert between the two?  It's not documented in either the BP solver or the main documentation.

**Comment by giorgioangel** [comment]
Just added a function in this new version here: https://github.com/schillij95/ThaumatoAnakalyptor/tree/main/ThaumatoAnakalyptor/BP_node_deactivation
