### ISSUE TITLE
Readme Spelling mistake

### ISSUE THREAD

**Issue by Taazar** [schillij95/ThaumatoAnakalyptor#4]
Hey, love the project, just noticed a small spelling mistake in the read me, "eighter" should be "either" in the "Execute the Pipeline", "GUI" section. See attached line number:

https://github.com/schillij95/ThaumatoAnakalyptor/blob/dfc0a8d34df82a79e67d49df4dd003a6359bb068/README.md?plain=1#L94

**Comment by schillij95** [comment]
Thank you, commit 45ff156446d4130cafa92d280e9cb490fb1f7537 fixed it.
