### ISSUE TITLE
[Question] How do you remove the noise from the images

### ISSUE THREAD

**Issue by NoahSteam** [schillij95/ThaumatoAnakalyptor#5]
Amazing work on this!  I had looked into creating an auto-segmenter a while back but I struggled with sorting out the noise from the actual sheets.  Are you just cutting out anything below a certain intensity?  I imagine it's more involved than that though.  From what I understand, you generate side images from the top/down ones that are provided and then use that figure out the edges(?), but what about all the nose in the images that isn't part of the sheet itself?

**Comment by schillij95** [comment]
Hi Noah,
I employ Gaussian Blurring to smooth out some of the noise. To extract the surface points of the sheets, Thaumato analyzes the 3D derivatives of the 3D scroll scan.

I am writing a technical report about ThaumatoAnakalyptor, it should be ready some time this week.

Cheers

**Comment by schillij95** [comment]
Hi Noah

I added a Technical Report and Roadmap for ThaumatoAnakalyptor here: https://github.com/schillij95/ThaumatoAnakalyptor/blob/main/documentation/ThaumatoAnakalyptor___Technical_Report_and_Roadmap.pdf

Any improvements to the repository or documentation are most welcome.

Regards, Julian
